### ISSUE TITLE
2.6xpu on ubuntu24.04lts build failed

### ISSUE THREAD

**Issue by quantwin** [intel/intel-extension-for-pytorch#803]
### Describe the issue

follow this guide,

https://pytorch-extension.intel.com/installation?platform=gpu&version=v2.6.10%2Bxpu&os=linux%2Fwsl2&package=source

https://dgpu-docs.intel.com/driver/client/overview.html#installing-client-gpus-on-ubuntu-desktop-24-04-lts

run sh as below, (only ultra9 185H)

`~/Downloads/ipex_bundle$ bash compile_bundle.sh /opt/intel/oneapi mtl`

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.3/26.3 MB 16.4 MB/s eta 0:00:00
Collecting umf==0.10.* (from intel-cmplr-lib-ur==2025.1.0->intel-openmp<2026,>=2024->mkl-static)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/66/a4/1d289b37333a7c9a54d590d04a4d83aefa0e3d1ab1ad98e592d22080347a/umf-0.10.0-py2.py3-none-manylinux_2_28_x86_64.whl (314 kB)
Installing collected packages: tcmlib, mkl-include, umf, tbb, tbb-devel, intel-cmplr-lib-ur, intel-openmp, mkl-static
  Attempting uninstall: tcmlib
    Found existing installation: tcmlib 1.2.0
    Uninstalling tcmlib-1.2.0:
      Successfully uninstalled tcmlib-1.2.0
  Attempting uninstall: umf
    Found existing installation: umf 0.9.1
    Uninstalling umf-0.9.1:
      Successfully uninstalled umf-0.9.1
  Attempting uninstall: tbb
    Found existing installation: tbb 2022.1.0
    Uninstalling tbb-2022.1.0:
      Successfully uninstalled tbb-2022.1.0
  Attempting uninstall: intel-cmplr-lib-ur
    Found existing installation: intel-cmplr-lib-ur 2025.0.2
    Uninstalling intel-cmplr-lib-ur-2025.0.2:
      Successfully uninstalled intel-cmplr-lib-ur-2025.0.2
  Attempting uninstall: intel-openmp
    Found existing installation: intel-openmp 2025.0.2
    Uninstalling intel-openmp-2025.0.2:
      Successfully uninstalled intel-openmp-2025.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dpcpp-cpp-rt 2025.0.2 requires intel-openmp==2025.0.2, but you have intel-openmp 2025.1.0 which is incompatible.
intel-sycl-rt 2025.0.2 requires intel-cmplr-lib-ur==2025.0.2, but you have intel-cmplr-lib-ur 2025.1.0 which is incompatible.
Successfully installed intel-cmplr-lib-ur-2025.1.0 intel-openmp-2025.1.0 mkl-include-2025.1.0 mkl-static-2025.1.0 tbb-2022.1.0 tbb-devel-2022.1.0 tcmlib-1.3.0 umf-0.10.0
Building wheel torch-2.6.0a0+git1eba9b3
pytorch_extra_install_requirements: intel-cmplr-lib-rt==2025.0.2|intel-cmplr-lib-ur==2025.0.2|intel-cmplr-lic-rt==2025.0.2|intel-sycl-rt==2025.0.2|tcmlib==1.2.0|umf==0.9.1|intel-pti==0.10.0
running clean
-- The CXX compiler identification is GNU 13.3.0
-- The C compiler identification is GNU 13.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- _GLIBCXX_USE_CXX11_ABI=1 is already defined as a cmake variable
-- Not forcing any particular BLAS to be found
-- Could not find ccache. Consider installing ccache to speed up compilation.
-- Performing Test C_HAS_AVX_1
-- Performing Test C_HAS_AVX_1 - Failed
-- Performing Test C_HAS_AVX_2
-- Performing Test C_HAS_AVX_2 - Success
-- Performing Test C_HAS_AVX2_1
-- Performing Test C_HAS_AVX2_1 - Failed
-- Performing Test C_HAS_AVX2_2
-- Performing Test C_HAS_AVX2_2 - Success
-- Performing Test C_HAS_AVX512_1
-- Performing Test C_HAS_AVX512_1 - Failed
-- Performing Test C_HAS_AVX512_2
-- Performing Test C_HAS_AVX512_2 - Success
-- Performing Test CXX_HAS_AVX_1
-- Performing Test CXX_HAS_AVX_1 - Failed
-- Performing Test CXX_HAS_AVX_2
-- Performing Test CXX_HAS_AVX_2 - Success
-- Performing Test CXX_HAS_AVX2_1
-- Performing Test CXX_HAS_AVX2_1 - Failed
-- Performing Test CXX_HAS_AVX2_2
-- Performing Test CXX_HAS_AVX2_2 - Success
-- Performing Test CXX_HAS_AVX512_1
-- Performing Test CXX_HAS_AVX512_1 - Failed
-- Performing Test CXX_HAS_AVX512_2
-- Performing Test CXX_HAS_AVX512_2 - Success
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS - Success
-- Current compiler supports avx512f extension. Will build fbgemm.
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- Performing Test CXX_HAS_SVE256
-- Performing Test CXX_HAS_SVE256 - Failed
-- No SVE processor on this machine.
-- Compiler does not support SVE extension. Will not build perfkernels.
CMake Warning (dev) at /home/eastpeace/miniconda3/envs/pytorch310/lib/python3.10/site-packages/cmake/data/share/cmake-4.0/Modules/FindPackageHandleStandardArgs.cmake:430 (message):
  The package name passed to find_package_handle_standard_args() (SYCL) does
  not match the name of the calling package (SYCLToolkit).  This can lead to
  problems in calling code that expects find_package() result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindSYCLToolkit.cmake:125 (find_package_handle_standard_args)
  cmake/public/xpu.cmake:12 (find_package)
  cmake/Dependencies.cmake:93 (include)
  CMakeLists.txt:858 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found SYCL: /opt/intel/oneapi/compiler/2025.0/include;/opt/intel/oneapi/compiler/2025.0/include/sycl (found version "20250004")
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
CMake Error at third_party/protobuf/cmake/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.

-- Configuring incomplete, errors occurred!
Building wheel torch-2.6.0a0+git1eba9b3
-- Building version 2.6.0a0+git1eba9b3
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/eastpeace/Downloads/ipex_bundle/pytorch/torch -DCMAKE_PREFIX_PATH=/home/eastpeace/miniconda3/envs/pytorch310/lib/python3.10/site-packages;/home/eastpeace/miniconda3/envs/pytorch310:/opt/intel/oneapi/pti/0.10/lib/cmake/pti:/opt/intel/oneapi/mkl/2025.0/lib/cmake:/opt/intel/oneapi/compiler/2025.0 -DGLIBCXX_USE_CXX11_ABI=1 -DPython_EXECUTABLE=/home/eastpeace/miniconda3/envs/pytorch310/bin/python -DTORCH_BUILD_VERSION=2.6.0a0+git1eba9b3 -DTORCH_XPU_ARCH_LIST=mtl -DUSE_CUDA=0 -DUSE_MPI=0 -DUSE_NUMA=0 -DUSE_NUMPY=True -DUSE_STATIC_MKL=1 /home/eastpeace/Downloads/ipex_bundle/pytorch
(pytorch310) eastpeace@mylinux:~/Downloads/ipex_bundle$ ls

**Comment by quantwin** [comment]
I have integrated graphics only, but with large RAM.
~$ clinfo -l
Platform #0: Intel(R) OpenCL Graphics
 `-- Device #0: Intel(R) Arc(TM) Graphics

I'm too unsure if it's the cmake version that's causing the problem, because on this pc I tried the pip  in win11 (24H2), and even though it eventually worked, it also prompted a version conflict with these packages, strange uninstallation issues, but when I test in jupyterlab, I can see that the video card is working, it's just that the video memory isn't being fully utilized, and is only up to 8GB (the shared video memory is more than 48G, and the physical RAM is 96G)

**Comment by tye1** [comment]
CMake Error at third_party/protobuf/cmake/CMakeLists.txt:2 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.

>> It looks a known issue in PyTorch, which has been later resolved in https://github.com/pytorch/pytorch/pull/150460 in PyTorch 2.7.

also, you don't need build torch by yourself if you just want build IPEX from source.

**Comment by jrpike** [comment]
> also, you don't need build torch by yourself if you just want build IPEX from source.

How exactly am I to exclude cmake when building IPEX from source? The documentation makes no mention of this, nor are the setup scripts clear.

Regardless of any workarounds, the Intel-provided instructions here https://pytorch-extension.intel.com/installation?platform=gpu&version=v2.6.10%2Bxpu&os=linux%2Fwsl2&package=source are currently not working.

**Comment by jingxu10** [comment]
We were not aware of the cmake version issue until cmake 4 was released recently, same as the issue reported in https://github.com/pytorch/pytorch/pull/150460.
Please use `pip install "cmake<4"` to install cmake 3 then try again.
We will update the installation guide with the cmake version requirement.

**Comment by quantwin** [comment]
I'm just an fresh AI learner. I've attempted many times and encountered similar error messages. I'll test again once the official guidelines are updated, but until then, we'll refrain from any unnecessary attempts.

**Comment by tye1** [comment]
> > also, you don't need build torch by yourself if you just want build IPEX from source.
> 
> How exactly am I to exclude cmake when building IPEX from source? The documentation makes no mention of this, nor are the setup scripts clear.
> 
> Regardless of any workarounds, the Intel-provided instructions here https://pytorch-extension.intel.com/installation?platform=gpu&version=v2.6.10%2Bxpu&os=linux%2Fwsl2&package=source are currently not working.

@jingxu10  please help here.

**Comment by jingxu10** [comment]
Hi @quantwin , I updated the guideline.
Just wanna double check when you got the error at the beginning, was the cmake used 3.28.3?

**Comment by quantwin** [comment]
eastpeace@mylinux:~$ cmake --version
cmake version 3.28.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(base) eastpeace@mylinux:~$ sudo apt install -y intel-oneapi-dpcpp-cpp-2025.0=2025.0.4-1519 intel-oneapi-mkl-devel=2025.0.1-14 intel-oneapi-ccl-devel=2021.14.0-505 intel-pti-dev=0.10.0-284
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package intel-pti-dev is a virtual package provided by:
  intel-pti-dev-0.10 0.10.2-6
You should explicitly select one to install.

E: Unable to locate package intel-oneapi-mkl-devel
E: Unable to locate package intel-oneapi-ccl-devel
E: Version '0.10.0-284' for 'intel-pti-dev' was not found
(base) eastpeace@mylinux:~$

**Comment by quantwin** [comment]
~/ipex_bundle$ bash compile_bundle.sh /opt/intel/oneapi mtl
...

Updated 848 paths from the index
Already on 'main'
Note: switching to 'v0.21.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 7af698794e [Cherry-Pick] Update Requires-Python: >=3.9 (#8886)
Updated 830 paths from the index
Already on 'main'
Note: switching to 'v2.6.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at d8831425 [Cherry Pick] Update Supported Python version 3.9-3.13 (#3875)
Cloning into 'torch-ccl'...
remote: Enumerating objects: 2241, done.
remote: Counting objects: 100% (307/307), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 2241 (delta 280), reused 257 (delta 254), pack-reused 1934 (from 2)
Receiving objects: 100% (2241/2241), 663.68 KiB | 539.00 KiB/s, done.
Resolving deltas: 100% (1276/1276), done.
Updated 75 paths from the index
Already on 'master'
Note: switching to 'v2.6.0+xpu'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5398850 fix version
Submodule 'third_party/oneCCL' (https://github.com/uxlfoundation/oneCCL.git) registered for path 'third_party/oneCCL'
Cloning into '/home/eastpeace/ipex_bundle/torch-ccl/third_party/oneCCL'...
Submodule path 'third_party/oneCCL': checked out '3afa1bb7936f57683a2503c34b29c0daca6a9ccb'
WARNING: Skipping torch as it is not installed.
WARNING: Skipping torchvision as it is not installed.
WARNING: Skipping torchaudio as it is not installed.
WARNING: Skipping intel-extension-for-pytorch as it is not installed.
WARNING: Skipping intel-extension-for-pytorch-deepspeed as it is not installed.
WARNING: Skipping oneccl_bind_pt as it is not installed.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting cmake
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/91/96/2671d7f3612c4449affc956542b25d9193efd8026dbc8ab6b3498f5cede3/cmake-4.0.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 53.1 MB/s eta 0:00:00
Collecting make
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/71/8b/af4b541d2a6e1ea2021dc95f5fd75fc5679462e5b06b155eed65b25cc2eb/make-0.1.6.post2-py3-none-any.whl (14 kB)
Collecting ninja
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/eb/7a/455d2877fe6cf99886849c7f9755d897df32eaf3a0fba47b56e615f880f7/ninja-1.11.1.4-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (422 kB)
Collecting Jinja2 (from make)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl (134 kB)
Collecting jinja2-time (from make)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/a1/d44fa38306ffa34a7e1af09632b158e13ec89670ce491f8a15af3ebcb4e4/jinja2_time-0.2.0-py2.py3-none-any.whl (6.4 kB)
Collecting MarkupSafe>=2.0 (from Jinja2->make)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/22/35/137da042dfb4720b638d2937c38a9c2df83fe32d20e8c8f3185dbfef05f7/MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)
Collecting arrow (from jinja2-time->make)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f8/ed/e97229a566617f2ae958a6b13e7cc0f585470eac730a73e9e82c32a3cdd2/arrow-1.3.0-py3-none-any.whl (66 kB)
Collecting python-dateutil>=2.7.0 (from arrow->jinja2-time->make)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting types-python-dateutil>=2.8.10 (from arrow->jinja2-time->make)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0f/b3/ca41df24db5eb99b00d97f89d7674a90cb6b3134c52fb8121b6d8d30f15c/types_python_dateutil-2.9.0.20241206-py3-none-any.whl (14 kB)
Collecting six>=1.5 (from python-dateutil>=2.7.0->arrow->jinja2-time->make)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: types-python-dateutil, six, ninja, MarkupSafe, cmake, python-dateutil, Jinja2, arrow, jinja2-time, make
Successfully installed Jinja2-3.1.6 MarkupSafe-3.0.2 arrow-1.3.0 cmake-4.0.0 jinja2-time-0.2.0 make-0.1.6.post2 ninja-1.11.1.4 python-dateutil-2.9.0.post0 six-1.17.0 types-python-dateutil-2.9.0.20241206
--2025-04-29 13:21:16--  https://github.com/NixOS/patchelf/releases/download/0.18.0/patchelf-0.18.0-x86_64.tar.gz
Connecting to 127.0.0.1:7897... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/2928164/b19cd60f-578c-4b91-a05b-a79ef6862e38?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250429%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250429T052117Z&X-Amz-Expires=300&X-Amz-Signature=bec7cd7541c560a729276ec8bf56c3546971c0cafdcaee2a2e73b6cb3970856d&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dpatchelf-0.18.0-x86_64.tar.gz&response-content-type=application%2Foctet-stream [following]
--2025-04-29 13:21:17--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/2928164/b19cd60f-578c-4b91-a05b-a79ef6862e38?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250429%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250429T052117Z&X-Amz-Expires=300&X-Amz-Signature=bec7cd7541c560a729276ec8bf56c3546971c0cafdcaee2a2e73b6cb3970856d&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dpatchelf-0.18.0-x86_64.tar.gz&response-content-type=application%2Foctet-stream
Connecting to 127.0.0.1:7897... connected.
Proxy request sent, awaiting response... 200 OK
Length: 457219 (447K) [application/octet-stream]
Saving to: ‘patchelf.tar.gz’

patchelf.tar.gz                100%[====================================================>] 446.50K   380KB/s    in 1.2s    

2025-04-29 13:21:20 (380 KB/s) - ‘patchelf.tar.gz’ saved [457219/457219]

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting astunparse (from -r requirements.txt (line 2))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting expecttest>=0.2.1 (from -r requirements.txt (line 3))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/27/fb/deeefea1ea549273817ca7bed3db2f39cc238a75a745a20e3651619f7335/expecttest-0.3.0-py3-none-any.whl (8.2 kB)
Collecting hypothesis (from -r requirements.txt (line 4))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/bd/e5/41a6733bfe11997795669dec3b3d785c28918e06568a2540dcc29f0d3fa7/hypothesis-6.131.9-py3-none-any.whl (499 kB)
Collecting numpy (from -r requirements.txt (line 5))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c2/70/fed13c70aabe7049368553e81d7ca40f305f305800a007a956d7cd2e5476/numpy-2.2.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 28.9 MB/s eta 0:00:00
Collecting psutil (from -r requirements.txt (line 6))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bf/b9/b0eb3f3cbcb734d930fdf839431606844a825b23eaf9a6ab371edac8162c/psutil-7.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (277 kB)
Collecting pyyaml (from -r requirements.txt (line 7))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6b/4e/1523cb902fd98355e2e9ea5e5eb237cbc5f3ad5f3075fa65087aa0ecb669/PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 751.2/751.2 kB 29.5 MB/s eta 0:00:00
Collecting requests (from -r requirements.txt (line 8))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f9/9b/335f9764261e915ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl (64 kB)
Requirement already satisfied: setuptools in /home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (75.8.0)
Collecting types-dataclasses (from -r requirements.txt (line 10))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/31/85/23ab2bbc280266af5bf22ded4e070946d1694d1721ced90666b649eaa795/types_dataclasses-0.6.6-py3-none-any.whl (2.9 kB)
Collecting typing-extensions>=4.10.0 (from -r requirements.txt (line 11))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8b/54/b1ae86c0973cc6f0210b53d508ca3641fb6d0c56823f288d108bc7ab3cc8/typing_extensions-4.13.2-py3-none-any.whl (45 kB)
Collecting sympy==1.13.1 (from -r requirements.txt (line 12))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b2/fe/81695a1aa331a842b582453b605175f419fe8540355886031328089d840a/sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 10.6 MB/s eta 0:00:00
Collecting filelock (from -r requirements.txt (line 13))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4d/36/2a115987e2d8c300a974597416d9de88f2444426de9571f4b59b2cca3acc/filelock-3.18.0-py3-none-any.whl (16 kB)
Collecting networkx (from -r requirements.txt (line 14))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b9/54/dd730b32ea14ea797530a4479b2ed46a6fb250f682a9cfb997e968bf0261/networkx-3.4.2-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 59.4 MB/s eta 0:00:00
Requirement already satisfied: jinja2 in /home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (3.1.6)
Collecting fsspec (from -r requirements.txt (line 16))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/44/4b/e0cfc1a6f17e990f3e64b7d941ddc4acdc7b19d6edd51abf495f32b1a9e4/fsspec-2025.3.2-py3-none-any.whl (194 kB)
Collecting lintrunner (from -r requirements.txt (line 17))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9b/2d/bbd16778a0d890617eb0f8d57674780da0c6b32fcffddb4933efb1403cea/lintrunner-0.12.7-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 15.4 MB/s eta 0:00:00
Requirement already satisfied: ninja in /home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (1.11.1.4)
Collecting packaging (from -r requirements.txt (line 19))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/20/12/38679034af332785aac8774540895e234f4d07f7545804097de4b666afd8/packaging-25.0-py3-none-any.whl (66 kB)
Collecting optree>=0.13.0 (from -r requirements.txt (line 20))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4b/f5/8b4ea051730c461e8957652ae58a895e5cc740b162adfe12f15d144d7c76/optree-0.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (397 kB)
Requirement already satisfied: cmake in /home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages (from -r requirements.txt (line 21)) (4.0.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->-r requirements.txt (line 12))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 13.0 MB/s eta 0:00:00
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages (from astunparse->-r requirements.txt (line 2)) (0.45.1)
Requirement already satisfied: six<2.0,>=1.6.1 in /home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages (from astunparse->-r requirements.txt (line 2)) (1.17.0)
Collecting attrs>=22.2.0 (from hypothesis->-r requirements.txt (line 4))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/77/06/bb80f5f86020c4551da315d78b3ab75e8228f89f0162f2c3a819e407941a/attrs-25.3.0-py3-none-any.whl (63 kB)
Collecting exceptiongroup>=1.0.0 (from hypothesis->-r requirements.txt (line 4))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/02/cc/b7e31358aac6ed1ef2bb790a9746ac2c69bcb3c8588b41616914eb106eaf/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Collecting sortedcontainers<3.0.0,>=2.1.0 (from hypothesis->-r requirements.txt (line 4))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting charset-normalizer<4,>=2 (from requests->-r requirements.txt (line 8))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/93/62/5e89cdfe04584cb7f4d36003ffa2936681b03ecc0754f8e969c2becb7e24/charset_normalizer-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (146 kB)
Collecting idna<4,>=2.5 (from requests->-r requirements.txt (line 8))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/76/c6/c88e154df9c4e1a2a66ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl (70 kB)
Collecting urllib3<3,>=1.21.1 (from requests->-r requirements.txt (line 8))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6b/11/cc635220681e93a0183390e26485430ca2c7b5f9d33b15c74c2861cb8091/urllib3-2.4.0-py3-none-any.whl (128 kB)
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 8))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4a/7e/3db2bd1b1f9e95f7cddca6d6e75e2f2bd9f51b1246e546d88addca0106bd/certifi-2025.4.26-py3-none-any.whl (159 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages (from jinja2->-r requirements.txt (line 15)) (3.0.2)
Installing collected packages: types-dataclasses, sortedcontainers, mpmath, urllib3, typing-extensions, sympy, pyyaml, psutil, packaging, numpy, networkx, lintrunner, idna, fsspec, filelock, expecttest, exceptiongroup, charset-normalizer, certifi, attrs, astunparse, requests, optree, hypothesis
Successfully installed astunparse-1.6.3 attrs-25.3.0 certifi-2025.4.26 charset-normalizer-3.4.1 exceptiongroup-1.2.2 expecttest-0.3.0 filelock-3.18.0 fsspec-2025.3.2 hypothesis-6.131.9 idna-3.10 lintrunner-0.12.7 mpmath-1.3.0 networkx-3.4.2 numpy-2.2.5 optree-0.15.0 packaging-25.0 psutil-7.0.0 pyyaml-6.0.2 requests-2.32.3 sortedcontainers-2.4.0 sympy-1.13.1 types-dataclasses-0.6.6 typing-extensions-4.13.2 urllib3-2.4.0
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting mkl-static
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/58/2a/33232c78f31a632698d64624a913b0249cf25c36d4f96b431fb4f3e04551/mkl_static-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (204.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.8/204.8 MB 40.3 MB/s eta 0:00:00
Collecting mkl-include
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f5/1b/2d050cbd9080520244c563a163e9a4daf285710a94e6713e9eaaa1718675/mkl_include-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 43.4 MB/s eta 0:00:00
Collecting intel-openmp<2026,>=2024 (from mkl-static)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/dd/0d/888c94d4df55b7deb17d1aca7c70d4caf77f4b41770455634d562c080154/intel_openmp-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (48.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.6/48.6 MB 47.3 MB/s eta 0:00:00
Collecting tbb-devel==2022.* (from mkl-static)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4d/0c/1a0e8c02af7fffd59e69cb2679ce4aa08103eaf2d7fa68b9f499be9b5606/tbb_devel-2022.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 21.6 MB/s eta 0:00:00
Collecting tbb==2022.1.0 (from tbb-devel==2022.*->mkl-static)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c6/64/3d24181aaea3fb892d4a46f8171845782ee364d60e9494426daf31d12f47/tbb-2022.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 17.8 MB/s eta 0:00:00
Collecting tcmlib==1.* (from tbb==2022.1.0->tbb-devel==2022.*->mkl-static)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/06/bb/09a6dc2f1110b409d6d2f96429969d7466bde9bf4ad8b2e682d851ef104b/tcmlib-1.3.0-py2.py3-none-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 21.1 MB/s eta 0:00:00
Collecting intel-cmplr-lib-ur==2025.1.0 (from intel-openmp<2026,>=2024->mkl-static)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/00/fb/94792cdb786c0289ba9ac7359ce377aebdc295a0e01bc919889d52e5a199/intel_cmplr_lib_ur-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (26.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.3/26.3 MB 16.8 MB/s eta 0:00:00
Collecting umf==0.10.* (from intel-cmplr-lib-ur==2025.1.0->intel-openmp<2026,>=2024->mkl-static)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/66/a4/1d289b37333a7c9a54d590d04a4d83aefa0e3d1ab1ad98e592d22080347a/umf-0.10.0-py2.py3-none-manylinux_2_28_x86_64.whl (314 kB)
Installing collected packages: tcmlib, mkl-include, umf, tbb, tbb-devel, intel-cmplr-lib-ur, intel-openmp, mkl-static
Successfully installed intel-cmplr-lib-ur-2025.1.0 intel-openmp-2025.1.0 mkl-include-2025.1.0 mkl-static-2025.1.0 tbb-2022.1.0 tbb-devel-2022.1.0 tcmlib-1.3.0 umf-0.10.0
Building wheel torch-2.6.0a0+git1eba9b3
pytorch_extra_install_requirements: intel-cmplr-lib-rt==2025.0.2|intel-cmplr-lib-ur==2025.0.2|intel-cmplr-lic-rt==2025.0.2|intel-sycl-rt==2025.0.2|tcmlib==1.2.0|umf==0.9.1|intel-pti==0.10.0
running clean
-- The CXX compiler identification is GNU 11.4.0
-- The C compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- _GLIBCXX_USE_CXX11_ABI=1 is already defined as a cmake variable
-- Not forcing any particular BLAS to be found
-- Could not find ccache. Consider installing ccache to speed up compilation.
-- Performing Test C_HAS_AVX_1
-- Performing Test C_HAS_AVX_1 - Failed
-- Performing Test C_HAS_AVX_2
-- Performing Test C_HAS_AVX_2 - Success
-- Performing Test C_HAS_AVX2_1
-- Performing Test C_HAS_AVX2_1 - Failed
-- Performing Test C_HAS_AVX2_2
-- Performing Test C_HAS_AVX2_2 - Success
-- Performing Test C_HAS_AVX512_1
-- Performing Test C_HAS_AVX512_1 - Failed
-- Performing Test C_HAS_AVX512_2
-- Performing Test C_HAS_AVX512_2 - Success
-- Performing Test CXX_HAS_AVX_1
-- Performing Test CXX_HAS_AVX_1 - Failed
-- Performing Test CXX_HAS_AVX_2
-- Performing Test CXX_HAS_AVX_2 - Success
-- Performing Test CXX_HAS_AVX2_1
-- Performing Test CXX_HAS_AVX2_1 - Failed
-- Performing Test CXX_HAS_AVX2_2
-- Performing Test CXX_HAS_AVX2_2 - Success
-- Performing Test CXX_HAS_AVX512_1
-- Performing Test CXX_HAS_AVX512_1 - Failed
-- Performing Test CXX_HAS_AVX512_2
-- Performing Test CXX_HAS_AVX512_2 - Success
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS - Success
-- Current compiler supports avx512f extension. Will build fbgemm.
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- Performing Test CXX_HAS_SVE256
-- Performing Test CXX_HAS_SVE256 - Failed
-- No SVE processor on this machine.
-- Compiler does not support SVE extension. Will not build perfkernels.
CMake Warning (dev) at /home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages/cmake/data/share/cmake-4.0/Modules/FindPackageHandleStandardArgs.cmake:430 (message):
  The package name passed to find_package_handle_standard_args() (SYCL) does
  not match the name of the calling package (SYCLToolkit).  This can lead to
  problems in calling code that expects find_package() result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindSYCLToolkit.cmake:125 (find_package_handle_standard_args)
  cmake/public/xpu.cmake:12 (find_package)
  cmake/Dependencies.cmake:93 (include)
  CMakeLists.txt:858 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found SYCL: /opt/intel/oneapi/compiler/2025.0/include;/opt/intel/oneapi/compiler/2025.0/include/sycl (found version "20250004")
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
CMake Error at third_party/protobuf/cmake/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.


-- Configuring incomplete, errors occurred!
Building wheel torch-2.6.0a0+git1eba9b3
-- Building version 2.6.0a0+git1eba9b3
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/eastpeace/ipex_bundle/pytorch/torch -DCMAKE_PREFIX_PATH=/home/eastpeace/miniconda3/envs/pytorchintel/lib/python3.10/site-packages;/home/eastpeace/miniconda3/envs/pytorchintel:/opt/intel/oneapi/pti/0.10/lib/cmake/pti:/opt/intel/oneapi/mkl/2025.0/lib/cmake:/opt/intel/oneapi/compiler/2025.0 -DGLIBCXX_USE_CXX11_ABI=1 -DPython_EXECUTABLE=/home/eastpeace/miniconda3/envs/pytorchintel/bin/python -DTORCH_BUILD_VERSION=2.6.0a0+git1eba9b3 -DTORCH_XPU_ARCH_LIST=mtl -DUSE_CUDA=0 -DUSE_MPI=0 -DUSE_NUMA=0 -DUSE_NUMPY=True -DUSE_STATIC_MKL=1 /home/eastpeace/ipex_bundle/pytorch

**Comment by jingxu10** [comment]
We just released 2.7. Would you try this latest version? There should be no such issue in 2.7.
https://pytorch-extension.intel.com/installation?platform=gpu&version=v2.7.10%2Bxpu&os=linux%2Fwsl2&package=source

**Comment by quantwin** [comment]
Yes, I tried following the latest guidelines and got further than version 2.6—closer to success, but still failed in the end. 

I switched to Windows 11 to complete this, and everything worked smoothly there. 

Life’s too short to waste time on these issues. For me, as long as it works, that’s enough—I don’t want to dig deeper into installation details.
